# Overrides defaultArgs to narrow kubelet preferred address types to InternalIP on EKS.
defaultArgs:
  - --cert-dir=/tmp
  - --kubelet-preferred-address-types=InternalIP
  - --kubelet-use-node-status-port
  - --metric-resolution=15s

resources:
  requests:
    cpu: 25m
    memory: 64Mi
  limits:
    cpu: 1000m
    memory: 1Gi

replicas: 1
