environments:
  - environment: local
    # local environment is kubernetes-only; AWS fields are placeholders
    aws_region: ""
    iam_role_plan: ""
    iam_role_apply: ""

  - environment: develop
    aws_region: us-east-1
    iam_role_plan: arn:aws:iam::559744160976:role/github-oidc-auth-develop-github-actions-role
    iam_role_apply: arn:aws:iam::559744160976:role/github-oidc-auth-develop-github-actions-role

  - environment: production
    aws_region: ap-northeast-1
    iam_role_plan: arn:aws:iam::559744160976:role/github-oidc-auth-production-github-actions-role
    iam_role_apply: arn:aws:iam::559744160976:role/github-oidc-auth-production-github-actions-role

directory_conventions:
  - root: "aws/{service}"
    stacks:
      - name: terragrunt
        directory: "envs/{environment}"

  - root: "github/{service}"
    stacks:
      - name: terragrunt
        directory: "envs/{environment}"

  - root: "kubernetes/components/{service}"
    stacks:
      - name: kubernetes
        directory: "{environment}"
