environments:
  production:
---
repositories:
  - name: opentelemetry
    url: https://open-telemetry.github.io/opentelemetry-helm-charts

releases:
  - name: opentelemetry-collector
    namespace: monitoring
    chart: opentelemetry/opentelemetry-collector
    version: "0.175.1"
    values:
      - values.yaml.gotmpl
