apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gitea
  namespace: flux-system
spec:
  interval: 10m
  path: ./infrastructures/gitea/overlays/k3d
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  # HealthCheckでGiteaの準備完了を確認
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: gitea
      namespace: gitea
  wait: true