environments:
  production:
---
repositories:
  - name: falcosecurity
    url: https://falcosecurity.github.io/charts

releases:
  - name: falco
    namespace: falco
    chart: falcosecurity/falco
    version: "9.1.0"
    values:
      - values.yaml.gotmpl
