apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: oauth2-proxy-google
  namespace: oauth2-proxy
spec:
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  refreshInterval: 1h
  target:
    name: oauth2-proxy-google
    creationPolicy: Owner
  data:
    - secretKey: client-id
      remoteRef:
        key: eks/oauth2-proxy/google
        property: client_id
    - secretKey: client-secret
      remoteRef:
        key: eks/oauth2-proxy/google
        property: client_secret
    - secretKey: cookie-secret
      remoteRef:
        key: eks/oauth2-proxy/google
        property: cookie_secret
