apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - grafana-admin-external-secret.yaml
  - holmes-alertmanager-external-secret.yaml
  - alertmanager-slack-notify-external-secret.yaml
