resources:
  - ./00-namespaces
  - ./aws-load-balancer-controller
  - ./cilium
  - ./external-dns
  - ./fluent-bit
  - ./gateway-api
  - ./karpenter
  - ./keda
  - ./loki
  - ./metrics-server
  - ./mimir
  - ./prometheus-operator
