environments:
  production:
    # Parent values are not auto-inherited by child helmfiles in helmfile v1.4, requiring explicit redefinition.
    values:
      - loki:
          bucketName: loki-337169763788
          bucketPathPrefix: production
---
repositories:
  - name: grafana-community
    url: https://grafana-community.github.io/helm-charts

releases:
  - name: loki
    namespace: monitoring
    chart: grafana-community/loki
    version: "18.13.1"
    values:
      - values.yaml.gotmpl
