environments:
  production:

---
repositories:
  - name: codecentric
    url: https://codecentric.github.io/helm-charts

releases:
  - name: keycloak
    namespace: keycloak
    chart: codecentric/keycloakx
    version: "7.3.2"
    values:
      - values.yaml.gotmpl
