environments:
  production:
---
repositories:
  - name: robusta
    url: https://robusta-charts.storage.googleapis.com

releases:
  - name: holmesgpt
    namespace: holmesgpt
    chart: robusta/holmes
    version: "0.43.0"
    values:
      - values.yaml.gotmpl
