environments:
  production:
---
repositories:
  - name: grafana
    url: https://grafana.github.io/helm-charts

releases:
  - name: beyla
    namespace: monitoring
    chart: grafana/beyla
    version: "1.16.11"
    values:
      - values.yaml.gotmpl
