apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-admin
  namespace: keycloak
spec:
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  refreshInterval: 1h
  target:
    name: keycloak-admin
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: eks/keycloak/admin
        property: username
    - secretKey: password
      remoteRef:
        key: eks/keycloak/admin
        property: password
