apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: flux-system
spec:
  interval: 30m
  dependsOn:
    - name: prometheus-operator-crds
      namespace: flux-system
  chart:
    spec:
      chart: cilium
      version: "1.17.6"
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: flux-system
  targetNamespace: kube-system
  install:
    createNamespace: false
  values:
    # kube-proxy replacement
    kubeProxyReplacement: true

    # eBPF-based service mesh
    bpf:
      masquerade: true

    # Hubble observability
    hubble:
      relay:
        enabled: true
      ui:
        enabled: true
        ingress:
          enabled: false  # Gateway API使用のため無効
      metrics:
        enabled:
          - dns
          - drop
          - tcp
          - flow
          - port-distribution
          - icmp
          - httpV2
        serviceMonitor:
          enabled: true

    # Prometheus integration
    prometheus:
      enabled: true
      serviceMonitor:
        enabled: true

    # Gateway API support
    gatewayAPI:
      enabled: true

    # Service mesh features
    l7Proxy: true

    # k3d環境での設定
    operator:
      replicas: 1  # k3d単一ノードでのHost Port競合回避

    # k3s ServiceLBとの連携
    ipam:
      operator:
        clusterPoolIPv4PodCIDRList: ["10.42.0.0/16"]

    # Resources
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi
