environments:
  production:
---
repositories:
  - name: oauth2-proxy
    url: https://oauth2-proxy.github.io/manifests

# Multiple releases are deployed because oauth2-proxy upstreams config does not support host-based routing.
releases:
  - name: oauth2-proxy-grafana
    namespace: oauth2-proxy
    chart: oauth2-proxy/oauth2-proxy
    version: "10.7.1"
    values:
      - values.yaml.gotmpl
  - name: oauth2-proxy-hubble
    namespace: oauth2-proxy
    chart: oauth2-proxy/oauth2-proxy
    version: "10.7.1"
    values:
      - values.yaml.gotmpl
  - name: oauth2-proxy-alertmanager
    namespace: oauth2-proxy
    chart: oauth2-proxy/oauth2-proxy
    version: "10.7.1"
    values:
      - values.yaml.gotmpl
  - name: oauth2-proxy-prometheus
    namespace: oauth2-proxy
    chart: oauth2-proxy/oauth2-proxy
    version: "10.7.1"
    values:
      - values.yaml.gotmpl
