name: 'CI Gatekeeper'

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - '**'

permissions:
  actions: read

jobs:
  ci-gatekeeper:
    name: CI Gatekeeper
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Wait for other workflows
        uses: int128/wait-for-workflows-action@0e537e6178889f2339a37912dce46d725583b668 # v1.84.0
        with:
          max-timeout-seconds: 1800 # 30 minutes
