name: 'CI Gatekeeper'

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - '**'

permissions:
  actions: read

jobs:
  ci-gatekeeper:
    name: CI Gatekeeper
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Wait for other workflows
        uses: int128/wait-for-workflows-action@ad266067e3fee2dc057098d6bfeb835d960d04d4 # v1.86.0
        with:
          max-timeout-seconds: 1800 # 30 minutes
