name: 'CI Gatekeeper'

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - '**'

permissions:
  actions: read

jobs:
  ci-gatekeeper:
    name: CI Gatekeeper
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Wait for other workflows
        uses: int128/wait-for-workflows-action@f0dd035278e6fcb73d6be27e412dfff930fb2d10 # v1.98.0
        with:
          max-timeout-seconds: 1800 # 30 minutes
