environments:
  production:
    # Parent values are not auto-inherited by child helmfiles in helmfile v1.4, requiring explicit redefinition.
    values:
      - mimir:
          bucketName: mimir-337169763788
          bucketPathPrefix: production
---
repositories:
  - name: grafana
    url: https://grafana.github.io/helm-charts

releases:
  - name: mimir-distributed
    namespace: monitoring
    chart: grafana/mimir-distributed
    version: "6.2.1"
    values:
      - values.yaml.gotmpl
